POST http://localhost:3003/triagem-student
Content-Type: application/json

 {
"idAluno" : 8,
"serie" : 2,
"nascimento" : "2022-02-02",
"dataTriagem" : "2002-02-22", 
"idProfessor" : 5, 
"psicopedagogo" : "DARLAN",
"n1_n1" : "b", 
"n1_n2" : "b", 
"n1_n3" : "b", 
"n1_n4" : "b", 
"n1_n5" : "b", 
"n1_n6" : "b", 
"n1_n7" : "b", 
"n1_n8" : "b", 
"n1_n9" : "b", 
"n1_n10" : "b", 
"n1_n11" : "b",
"n2_n1" : "b", 
"n2_n2" : "b", 
"n2_n3" : "b", 
"n2_n4" : "b",
"n3_n1" : "b", 
"n3_n2" : "b", 
"n3_n3" : "b", 
"n3_n4" : "b",
"n4_n1" : "b", 
"n4_n2" : "b", 
"n4_n3" : "b", 
"n4_n4" : "b",
"mt_n1" : "b", 
"mt_n2" : "b", 
"mt_n3" : "b", 
"mt_n4" : "b", 
"mt_n5" : "b", 
"mt_n6" : "b", 
"mt_n7" : "b", 
"mt_n8" : "b", 
"mt_n9" : "b", 
"mt_n10" : "b", 
"mt_n11" : "b",
"hc_n1" : "b", 
"hc_n2" : "b", 
"hc_n3" : "b", 
"hc_n4" : "b", 
"hc_n5" : "b", 
"hc_n6" : "b", 
"hc_n7" : "b", 
"hc_n8" : "b", 
"hc_n9" : "b", 
"hc_n10" : "b", 
"hc_n11" : "b", 
"hc_n12" : "b", 
"hc_n13" : "b", 
"hc_n14" : "b", 
"hc_n15" : "b", 
"hc_n16" : "b", 
"hc_n17" : "b"


 }



<!-->
 
POST http://localhost:3003/sign-up-student
Content-Type: application/json

 {
"nome" : "antonio",
"sexo" : "M",
"nascimento" : "2052-01-12",
"religiao" : "brasileiro",
"am_p1" : "a",
"am_p2" : "a",
"am_p3" : "a",
"ap_p1" : "a",
"ap_p2" : "a",
"ap_p3" : "a",
"ap_p4" : "a",
"a_p1" : "a",
"d_p1" : "a",
"d_p2" : "a",
"d_p3" : "a",
"d_p4" : "a",
"d_p5" : "a",
"d_p6" : "a",
"d_p7" : "a",
"d_p8" : "a",
"d_p9" : "a",
"d_p10" : "a",
"d_p11" : "a",
"d_p12" : "a",
"d_p13" : "a",
"d_p14" : "a",
"medidas" : "a",
"contrariado" : "a",
"saude" : "a",
"acompanhamento" : "a",
"apoio" : "a",
"h_p1" : "a",
"h_p2" : "a",
"h_p3" : "a",
"h_p4" : "a",
"h_p5" : "a",
"h_p6" : "a",
"h_p7" : "a",
"h_p8" : "a",
"h_p9" : "a",
"h_p10" : "a"
}