POST http://localhost:3003/sign-up-student
Content-Type: application/json

 {
"nome" : "matheus",
"sexo" : "12345678987",
"nascimento" : "2000-01-01",
"religiao" : "mdmdmdm@gmail.com",
"am_p1" : "a",
"am_p2" : "a",
"am_p3" : "a",
"ap_p1" : "a",
"ap_p2" : "a",
"ap_p3" : "a",
"ap_p4" : "a",
"a_p1" : "a",
"d_p1" : "a",
"d_p2" : "a",
"d_p3" : "a",
"d_p4" : "a",
"d_p5" : "a",
"d_p6" : "a",
"d_p7" : "a",
"d_p8" : "a",
"d_p9" : "a",
"d_p10" : "a",
"d_p11" : "a",
"d_p12" : "a",
"d_p13" : "a",
"d_p14" : "a",
"f_p1" : "a",
"f_p2" : "a",
"f_p3" : "a",
"f_p4" : "a",
"f_p5" : "a",
"f_p6" : "a",
"h_p1" : "a",
"h_p2" : "a",
"h_p3" : "a",
"h_p4" : "a",
"h_p5" : "a",
"h_p6" : "a",
"h_p7" : "a",
"h_p8" : "a",
"h_p9" : "a",
"h_p10" : "a",
}